/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.software.ui;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
 * @author Omar Khatib
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }
    public String name="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        AdminTabbedPane = new javax.swing.JTabbedPane();
        WelcomePanel = new javax.swing.JPanel();
        UserManagementPanel = new javax.swing.JPanel();
        UserManageTools = new javax.swing.JPanel();
        ManageAccLabel = new javax.swing.JLabel();
        UserMngUsernameTxt = new javax.swing.JTextField();
        UserMngPasswordTxt = new javax.swing.JTextField();
        UserMngEmailTxt = new javax.swing.JTextField();
        UserMngCityTxt = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        UserComboBox = new javax.swing.JComboBox<>();
        AddEditDeleteComboBox = new javax.swing.JComboBox<>();
        OkButton = new javax.swing.JButton();
        SolidLineLabel = new javax.swing.JLabel();
        MonitoringAndReportingPanel = new javax.swing.JPanel();
        MonitoAndRepTools = new javax.swing.JPanel();
        MonitoAndRepLabel = new javax.swing.JLabel();
        SolidLineLabel1 = new javax.swing.JLabel();
        ProfitsBtn = new javax.swing.JButton();
        BestSellingBtn = new javax.swing.JButton();
        StatisticsBtn = new javax.swing.JButton();
        ContentManagementPanel = new javax.swing.JPanel();
        ContentMngTools = new javax.swing.JPanel();
        ContentMngLabel = new javax.swing.JLabel();
        SolidLineLabel2 = new javax.swing.JLabel();
        ShowPostsBtn = new javax.swing.JButton();
        ShowRecipesBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ContentMngTextArea = new javax.swing.JTextArea();
        AdminBtnsPanel = new javax.swing.JPanel();
        UserMngBtn = new javax.swing.JButton();
        MonitAndRepBtn = new javax.swing.JButton();
        ContentMngBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        WelcomeAdminLabel = new javax.swing.JLabel();
        CakeImage = new javax.swing.JLabel();
        CE121Label = new javax.swing.JLabel();
        BackgroundPanel = new javax.swing.JPanel();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminTabbedPane.setBackground(new java.awt.Color(255, 255, 255,0));

        WelcomePanel.setBackground(new java.awt.Color(255, 255, 255,0));

        javax.swing.GroupLayout WelcomePanelLayout = new javax.swing.GroupLayout(WelcomePanel);
        WelcomePanel.setLayout(WelcomePanelLayout);
        WelcomePanelLayout.setHorizontalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        WelcomePanelLayout.setVerticalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );

        AdminTabbedPane.addTab("tab4", WelcomePanel);

        UserManagementPanel.setBackground(new java.awt.Color(255, 255, 255,0));

        UserManageTools.setBackground(new java.awt.Color(255, 255, 255,150));

        ManageAccLabel.setBackground(new java.awt.Color(0, 0, 0));
        ManageAccLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ManageAccLabel.setForeground(new java.awt.Color(0, 0, 0));
        ManageAccLabel.setText("Manage Accounts");

        UserMngUsernameTxt.setBackground(new java.awt.Color(255, 255, 255));
        UserMngUsernameTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserMngUsernameTxt.setForeground(new java.awt.Color(0, 0, 0));

        UserMngPasswordTxt.setBackground(new java.awt.Color(255, 255, 255));
        UserMngPasswordTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserMngPasswordTxt.setForeground(new java.awt.Color(0, 0, 0));

        UserMngEmailTxt.setBackground(new java.awt.Color(255, 255, 255));
        UserMngEmailTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserMngEmailTxt.setForeground(new java.awt.Color(0, 0, 0));

        UserMngCityTxt.setBackground(new java.awt.Color(255, 255, 255));
        UserMngCityTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserMngCityTxt.setForeground(new java.awt.Color(0, 0, 0));

        UsernameLabel.setBackground(new java.awt.Color(0, 0, 0));
        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        UsernameLabel.setText("Username:");

        EmailLabel.setBackground(new java.awt.Color(0, 0, 0));
        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(0, 0, 0));
        EmailLabel.setText("Email:");

        PasswordLabel.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel.setText("Password:");

        CityLabel.setBackground(new java.awt.Color(0, 0, 0));
        CityLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CityLabel.setForeground(new java.awt.Color(0, 0, 0));
        CityLabel.setText("City:");

        UserComboBox.setBackground(new java.awt.Color(255, 255, 255));
        UserComboBox.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        UserComboBox.setForeground(new java.awt.Color(0, 0, 0));
        UserComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Store Owner", "Supplier" }));

        AddEditDeleteComboBox.setBackground(new java.awt.Color(255, 255, 255));
        AddEditDeleteComboBox.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddEditDeleteComboBox.setForeground(new java.awt.Color(0, 0, 0));
        AddEditDeleteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add", "Edit", "Delete" }));

        OkButton.setBackground(new java.awt.Color(222, 115, 0));
        OkButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        OkButton.setForeground(new java.awt.Color(0, 0, 0));
        OkButton.setText("OK");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        SolidLineLabel.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\Line.png")); // NOI18N

        javax.swing.GroupLayout UserManageToolsLayout = new javax.swing.GroupLayout(UserManageTools);
        UserManageTools.setLayout(UserManageToolsLayout);
        UserManageToolsLayout.setHorizontalGroup(
            UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserManageToolsLayout.createSequentialGroup()
                .addGroup(UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserManageToolsLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(ManageAccLabel))
                    .addGroup(UserManageToolsLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(UserManageToolsLayout.createSequentialGroup()
                                .addComponent(UsernameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserMngUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UserManageToolsLayout.createSequentialGroup()
                                .addComponent(EmailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserMngEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(104, 104, 104)
                        .addGroup(UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(UserManageToolsLayout.createSequentialGroup()
                                .addComponent(CityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserMngCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UserManageToolsLayout.createSequentialGroup()
                                .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserMngPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(UserManageToolsLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(SolidLineLabel)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserManageToolsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddEditDeleteComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(310, 310, 310))
        );
        UserManageToolsLayout.setVerticalGroup(
            UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserManageToolsLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(ManageAccLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SolidLineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserMngPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserMngUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserMngCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserMngEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(UserComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddEditDeleteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OkButton)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout UserManagementPanelLayout = new javax.swing.GroupLayout(UserManagementPanel);
        UserManagementPanel.setLayout(UserManagementPanelLayout);
        UserManagementPanelLayout.setHorizontalGroup(
            UserManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserManagementPanelLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(UserManageTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        UserManagementPanelLayout.setVerticalGroup(
            UserManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserManagementPanelLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(UserManageTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        AdminTabbedPane.addTab("tab1", UserManagementPanel);

        MonitoringAndReportingPanel.setBackground(new java.awt.Color(255, 255, 255,0));

        MonitoAndRepTools.setBackground(new java.awt.Color(255, 255, 255,150));

        MonitoAndRepLabel.setBackground(new java.awt.Color(0, 0, 0));
        MonitoAndRepLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        MonitoAndRepLabel.setForeground(new java.awt.Color(0, 0, 0));
        MonitoAndRepLabel.setText("Monitoring & Reporting");

        SolidLineLabel1.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\Line.png")); // NOI18N

        ProfitsBtn.setBackground(new java.awt.Color(222, 115, 0));
        ProfitsBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ProfitsBtn.setForeground(new java.awt.Color(0, 0, 0));
        ProfitsBtn.setText("Profits");
        ProfitsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfitsBtnActionPerformed(evt);
            }
        });

        BestSellingBtn.setBackground(new java.awt.Color(222, 115, 0));
        BestSellingBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        BestSellingBtn.setForeground(new java.awt.Color(0, 0, 0));
        BestSellingBtn.setText("Best Selling");
        BestSellingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BestSellingBtnActionPerformed(evt);
            }
        });

        StatisticsBtn.setBackground(new java.awt.Color(222, 115, 0));
        StatisticsBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        StatisticsBtn.setForeground(new java.awt.Color(0, 0, 0));
        StatisticsBtn.setText("Statistics");

        javax.swing.GroupLayout MonitoAndRepToolsLayout = new javax.swing.GroupLayout(MonitoAndRepTools);
        MonitoAndRepTools.setLayout(MonitoAndRepToolsLayout);
        MonitoAndRepToolsLayout.setHorizontalGroup(
            MonitoAndRepToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MonitoAndRepToolsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MonitoAndRepLabel)
                .addGap(240, 240, 240))
            .addGroup(MonitoAndRepToolsLayout.createSequentialGroup()
                .addGroup(MonitoAndRepToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MonitoAndRepToolsLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(SolidLineLabel1))
                    .addGroup(MonitoAndRepToolsLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addGroup(MonitoAndRepToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BestSellingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProfitsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StatisticsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        MonitoAndRepToolsLayout.setVerticalGroup(
            MonitoAndRepToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MonitoAndRepToolsLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(MonitoAndRepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SolidLineLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(ProfitsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BestSellingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StatisticsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MonitoringAndReportingPanelLayout = new javax.swing.GroupLayout(MonitoringAndReportingPanel);
        MonitoringAndReportingPanel.setLayout(MonitoringAndReportingPanelLayout);
        MonitoringAndReportingPanelLayout.setHorizontalGroup(
            MonitoringAndReportingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MonitoringAndReportingPanelLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(MonitoAndRepTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        MonitoringAndReportingPanelLayout.setVerticalGroup(
            MonitoringAndReportingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MonitoringAndReportingPanelLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(MonitoAndRepTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        AdminTabbedPane.addTab("tab2", MonitoringAndReportingPanel);

        ContentManagementPanel.setBackground(new java.awt.Color(255, 255, 255,0));

        ContentMngTools.setBackground(new java.awt.Color(255, 255, 255,150));

        ContentMngLabel.setBackground(new java.awt.Color(0, 0, 0));
        ContentMngLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ContentMngLabel.setForeground(new java.awt.Color(0, 0, 0));
        ContentMngLabel.setText("Content Management");

        SolidLineLabel2.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\Line.png")); // NOI18N

        ShowPostsBtn.setBackground(new java.awt.Color(222, 115, 0));
        ShowPostsBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ShowPostsBtn.setForeground(new java.awt.Color(0, 0, 0));
        ShowPostsBtn.setText("Show Posts");
        ShowPostsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPostsBtnActionPerformed(evt);
            }
        });

        ShowRecipesBtn.setBackground(new java.awt.Color(222, 115, 0));
        ShowRecipesBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ShowRecipesBtn.setForeground(new java.awt.Color(0, 0, 0));
        ShowRecipesBtn.setText("Show Recipes");
        ShowRecipesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowRecipesBtnActionPerformed(evt);
            }
        });

        ContentMngTextArea.setEditable(false);
        ContentMngTextArea.setColumns(20);
        ContentMngTextArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ContentMngTextArea.setForeground(new java.awt.Color(0, 0, 0));
        ContentMngTextArea.setRows(5);
        jScrollPane1.setViewportView(ContentMngTextArea);

        javax.swing.GroupLayout ContentMngToolsLayout = new javax.swing.GroupLayout(ContentMngTools);
        ContentMngTools.setLayout(ContentMngToolsLayout);
        ContentMngToolsLayout.setHorizontalGroup(
            ContentMngToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentMngToolsLayout.createSequentialGroup()
                .addGroup(ContentMngToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentMngToolsLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(SolidLineLabel2))
                    .addGroup(ContentMngToolsLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(ContentMngLabel)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentMngToolsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ContentMngToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContentMngToolsLayout.createSequentialGroup()
                        .addComponent(ShowPostsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ShowRecipesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
        );
        ContentMngToolsLayout.setVerticalGroup(
            ContentMngToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentMngToolsLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(ContentMngLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SolidLineLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ContentMngToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowPostsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowRecipesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContentManagementPanelLayout = new javax.swing.GroupLayout(ContentManagementPanel);
        ContentManagementPanel.setLayout(ContentManagementPanelLayout);
        ContentManagementPanelLayout.setHorizontalGroup(
            ContentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentManagementPanelLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(ContentMngTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        ContentManagementPanelLayout.setVerticalGroup(
            ContentManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentManagementPanelLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(ContentMngTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        AdminTabbedPane.addTab("tab3", ContentManagementPanel);

        getContentPane().add(AdminTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -40, 1080, 840));

        AdminBtnsPanel.setBackground(new java.awt.Color(255, 255, 255,150));

        UserMngBtn.setBackground(new java.awt.Color(222, 115, 0));
        UserMngBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UserMngBtn.setForeground(new java.awt.Color(0, 0, 0));
        UserMngBtn.setText("User Management");
        UserMngBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserMngBtnActionPerformed(evt);
            }
        });

        MonitAndRepBtn.setBackground(new java.awt.Color(222, 115, 0));
        MonitAndRepBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MonitAndRepBtn.setForeground(new java.awt.Color(0, 0, 0));
        MonitAndRepBtn.setText("Monitoring and Reporting");
        MonitAndRepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonitAndRepBtnActionPerformed(evt);
            }
        });

        ContentMngBtn.setBackground(new java.awt.Color(222, 115, 0));
        ContentMngBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ContentMngBtn.setForeground(new java.awt.Color(0, 0, 0));
        ContentMngBtn.setText("Content Management");
        ContentMngBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContentMngBtnActionPerformed(evt);
            }
        });

        LogOutBtn.setBackground(new java.awt.Color(0, 0, 0));
        LogOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LogOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBtn.setText("Logout");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        WelcomeAdminLabel.setBackground(new java.awt.Color(0, 0, 0));
        WelcomeAdminLabel.setFont(new java.awt.Font("MV Boli", 1, 30)); // NOI18N
        WelcomeAdminLabel.setText("Welcome Admin");
        WelcomeAdminLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WelcomeAdminLabelMouseClicked(evt);
            }
        });

        CakeImage.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\cake (1).png")); // NOI18N

        CE121Label.setBackground(new java.awt.Color(0, 0, 0));
        CE121Label.setFont(new java.awt.Font("Pristina", 1, 14)); // NOI18N
        CE121Label.setText("CE.121");

        javax.swing.GroupLayout AdminBtnsPanelLayout = new javax.swing.GroupLayout(AdminBtnsPanel);
        AdminBtnsPanel.setLayout(AdminBtnsPanelLayout);
        AdminBtnsPanelLayout.setHorizontalGroup(
            AdminBtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminBtnsPanelLayout.createSequentialGroup()
                .addGroup(AdminBtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminBtnsPanelLayout.createSequentialGroup()
                        .addGroup(AdminBtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminBtnsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(AdminBtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MonitAndRepBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ContentMngBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UserMngBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(AdminBtnsPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(WelcomeAdminLabel))
                            .addGroup(AdminBtnsPanelLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(AdminBtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AdminBtnsPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(CE121Label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CakeImage))))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(AdminBtnsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AdminBtnsPanelLayout.setVerticalGroup(
            AdminBtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminBtnsPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(WelcomeAdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(UserMngBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(MonitAndRepBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(ContentMngBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(LogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(CakeImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CE121Label)
                .addGap(100, 100, 100))
        );

        getContentPane().add(AdminBtnsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 800));

        BackgroundImage.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\Background2.jpg")); // NOI18N

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BackgroundImage)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BackgroundImage)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(BackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        
    private String getFileName(String userType) {
        switch (userType) {
            case "User":
                return "Users.txt";
            case "Store Owner":
                return "Owners.txt";
            case "Supplier":
                return "Suppliers.txt";
            default:
                return null;
        }
    }
    private void addEntry(String fileName) throws IOException {
     List<String> lines = Files.readAllLines(Paths.get(fileName));
    String username = UserMngUsernameTxt.getText();
    boolean exists = false;

    // Check if the username already exists
    for (String line : lines) {
        if (line.startsWith(username + ",")) {
            exists = true;
            break;
        }
    }

    if (exists) {
        JOptionPane.showMessageDialog(this, "Username already exists. Please choose a different username.");
    } else {
        // If the username doesn't exist, add the new entry
        String newEntry = String.format("%s,%s,%s,%s",
                username,
                UserMngPasswordTxt.getText(),
                UserMngEmailTxt.getText(),
                UserMngCityTxt.getText());
        
        Files.write(Paths.get(fileName), (newEntry + System.lineSeparator()).getBytes(), StandardOpenOption.APPEND);
        JOptionPane.showMessageDialog(this, "User Added Successfully.");
        
        // Clear the text fields
        UserMngUsernameTxt.setText("");
        UserMngPasswordTxt.setText("");
        UserMngEmailTxt.setText("");
        UserMngCityTxt.setText("");
    }
}
    private void editEntry(String fileName) throws IOException {
        List<String> lines = Files.readAllLines(Paths.get(fileName));
        String username = UserMngUsernameTxt.getText();
        boolean found = false;

        for (int i = 0; i < lines.size(); i++) {
            if (lines.get(i).startsWith(username + ",")) {
                String updatedEntry = String.format("%s,%s,%s,%s",
                        username,
                        UserMngPasswordTxt.getText(),
                        UserMngEmailTxt.getText(),
                        UserMngCityTxt.getText());
                lines.set(i, updatedEntry);
                found = true;
                break;
            }
        }

        if (found) {
            Files.write(Paths.get(fileName), lines);
            JOptionPane.showMessageDialog(this, "The User Updated Successfully.");
            UserMngUsernameTxt.setText("");
            UserMngPasswordTxt.setText("");
            UserMngEmailTxt.setText("");
            UserMngCityTxt.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "The User Not Found.");
        }
    }
    private void deleteEntry(String fileName) throws IOException {
        List<String> lines = Files.readAllLines(Paths.get(fileName));
        String username = UserMngUsernameTxt.getText();
        List<String> updatedLines = lines.stream()
                .filter(line -> !line.startsWith(username + ","))
                .collect(Collectors.toList());

        if (updatedLines.size() < lines.size()) {
            // Show confirmation dialog
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to delete the user " + username + "?",
                    "Confirm Deletion",
                    JOptionPane.YES_NO_OPTION);

            // If the user confirms the deletion
            if (confirm == JOptionPane.YES_OPTION) {
                Files.write(Paths.get(fileName), updatedLines);
                JOptionPane.showMessageDialog(this, "The User Deleted Successfully.");
                UserMngUsernameTxt.setText("");
                UserMngPasswordTxt.setText("");
                UserMngEmailTxt.setText("");
                UserMngCityTxt.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Deletion cancelled.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "The User Not Found.");
        }
    }
    
    private void UserMngBtnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        AdminTabbedPane.setSelectedIndex(1);
    }                                          

    private void MonitAndRepBtnActionPerformed(java.awt.event.ActionEvent evt) {                                               
         AdminTabbedPane.setSelectedIndex(2);
    }                                              

    private void ContentMngBtnActionPerformed(java.awt.event.ActionEvent evt) {                                              
         AdminTabbedPane.setSelectedIndex(3);
         ContentMngTextArea.setText("");
    }                                             

    private void WelcomeAdminLabelMouseClicked(java.awt.event.MouseEvent evt) {                                               
         AdminTabbedPane.setSelectedIndex(0);
    }                                              

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.dispose();
        new LoginFrame().setVisible(true);
    }                                         

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String selectedUserType = (String) UserComboBox.getSelectedItem();
    String selectedOperation = (String) AddEditDeleteComboBox.getSelectedItem();
    String fileName = getFileName(selectedUserType);

    // Validate that all fields are filled
    if (UserMngUsernameTxt.getText().trim().isEmpty() ||
        UserMngPasswordTxt.getText().trim().isEmpty() ||
        UserMngEmailTxt.getText().trim().isEmpty() ||
        UserMngCityTxt.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields.");
        return;
    }

    if (fileName == null) {
        JOptionPane.showMessageDialog(this, "Invalid type selected.");
        return;
    }

    try {
        if ("Add".equalsIgnoreCase(selectedOperation)) {
            addEntry(fileName);
        } else if ("Edit".equalsIgnoreCase(selectedOperation)) {
            editEntry(fileName);
        } else if ("Delete".equalsIgnoreCase(selectedOperation)) {
            deleteEntry(fileName);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid operation selected.");
        }
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error processing the operation: " + ex.getMessage());
    }
    }                                        

    private void ProfitsBtnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {
            List<String> profits = Files.readAllLines(Paths.get("profits.txt"));
            if (profits.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No profits recorded yet.");
            } else {
                StringBuilder profitsMessage = new StringBuilder("All Recorded Profits:\n");
                for (String profit : profits) {
                    profitsMessage.append(profit).append("\n");
                }
                JOptionPane.showMessageDialog(this, profitsMessage.toString());
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error reading profits file: " + ex.getMessage());
        }
    }                                          

    private void BestSellingBtnActionPerformed(java.awt.event.ActionEvent evt) {                                               
        try {
        List<String> profits = Files.readAllLines(Paths.get("profits.txt"));
        if (profits.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No sales recorded yet.");
            return;
        }
        
        String bestSellingProduct = null;
        int maxSales = 0;
        String bestSellingInfo = null;

        for (String line : profits) {
            String[] parts = line.split(",");
            if (parts.length == 3) {
                String productName = parts[0].trim();
                int sales = Integer.parseInt(parts[1].trim());
                String moneyAchieved = parts[2].trim();

                if (sales > maxSales) {
                    maxSales = sales;
                    bestSellingProduct = productName;
                    bestSellingInfo = String.format("Product: %s\nNumber of Sales: %d\nMoney Achieved: %s.00$", 
                                                     productName, sales, moneyAchieved);
                }
            }
        }
        
        if (bestSellingProduct != null) {
            JOptionPane.showMessageDialog(this, "Best-Selling Product:\n" + bestSellingInfo);
        } else {
            JOptionPane.showMessageDialog(this, "Could not determine the best-selling product.");
        }
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error reading profits file: " + ex.getMessage());
    }
    }                                              

    private void ShowPostsBtnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        try {
        List<String> posts = Files.readAllLines(Paths.get("UserPosts.txt"));
        String content = String.join("\n", posts);
        ContentMngTextArea.setText(content);
        } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error reading UserPosts.txt: " + ex.getMessage());
        }
    }                                            

    private void ShowRecipesBtnActionPerformed(java.awt.event.ActionEvent evt) {                                               
        try {
        List<String> recipes = Files.readAllLines(Paths.get("UserRecipes.txt"));
        String content = String.join("\n", recipes);
        ContentMngTextArea.setText(content);
        } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "Error reading UserRecipes.txt: " + ex.getMessage());
        }   
    }                                              
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> AddEditDeleteComboBox;
    private javax.swing.JPanel AdminBtnsPanel;
    private javax.swing.JTabbedPane AdminTabbedPane;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JButton BestSellingBtn;
    private javax.swing.JLabel CE121Label;
    private javax.swing.JLabel CakeImage;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JPanel ContentManagementPanel;
    private javax.swing.JButton ContentMngBtn;
    private javax.swing.JLabel ContentMngLabel;
    private javax.swing.JTextArea ContentMngTextArea;
    private javax.swing.JPanel ContentMngTools;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JLabel ManageAccLabel;
    private javax.swing.JButton MonitAndRepBtn;
    private javax.swing.JLabel MonitoAndRepLabel;
    private javax.swing.JPanel MonitoAndRepTools;
    private javax.swing.JPanel MonitoringAndReportingPanel;
    private javax.swing.JButton OkButton;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton ProfitsBtn;
    private javax.swing.JButton ShowPostsBtn;
    private javax.swing.JButton ShowRecipesBtn;
    private javax.swing.JLabel SolidLineLabel;
    private javax.swing.JLabel SolidLineLabel1;
    private javax.swing.JLabel SolidLineLabel2;
    private javax.swing.JButton StatisticsBtn;
    private javax.swing.JComboBox<String> UserComboBox;
    private javax.swing.JPanel UserManageTools;
    private javax.swing.JPanel UserManagementPanel;
    private javax.swing.JButton UserMngBtn;
    private javax.swing.JTextField UserMngCityTxt;
    private javax.swing.JTextField UserMngEmailTxt;
    private javax.swing.JTextField UserMngPasswordTxt;
    private javax.swing.JTextField UserMngUsernameTxt;
    private javax.swing.JLabel UsernameLabel;
    public javax.swing.JLabel WelcomeAdminLabel;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
