/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.software.ui;

import javax.swing.JOptionPane;

/**
 *
 * @author Omar Khatib
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        MainTabbedPane = new javax.swing.JTabbedPane();
        LoginPanel = new javax.swing.JPanel();
        SweetLabel = new javax.swing.JLabel();
        ManagementLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        CakeImage = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        doesnt = new javax.swing.JLabel();
        signUpBtn = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        SignupPanel = new javax.swing.JPanel();
        SweetLabel2 = new javax.swing.JLabel();
        ManagementLabel2 = new javax.swing.JLabel();
        UsernameLabel2 = new javax.swing.JLabel();
        UsernameTextField2 = new javax.swing.JTextField();
        PasswordLabel2 = new javax.swing.JLabel();
        PasswordTextField2 = new javax.swing.JTextField();
        ConfirmPassLabel = new javax.swing.JLabel();
        ConfirmPassTextField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        CityLabel = new javax.swing.JLabel();
        CityComboBox = new javax.swing.JComboBox<>();
        SignUpBtnS = new javax.swing.JButton();
        Already = new javax.swing.JLabel();
        LoginBtnS = new javax.swing.JButton();
        UserCheckBox = new javax.swing.JCheckBox();
        OwnerCheckBox = new javax.swing.JCheckBox();
        SupplierCheckBox = new javax.swing.JCheckBox();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainTabbedPane.setBackground(new java.awt.Color(255, 255, 255,0));

        LoginPanel.setBackground(new java.awt.Color(140, 135, 135,180));
        LoginPanel.setForeground(new java.awt.Color(255, 255, 255));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SweetLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        SweetLabel.setForeground(new java.awt.Color(93, 56, 10));
        SweetLabel.setText("Sweet ");
        LoginPanel.add(SweetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        ManagementLabel.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        ManagementLabel.setForeground(new java.awt.Color(0, 0, 0));
        ManagementLabel.setText("Management System");
        LoginPanel.add(ManagementLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 324, 30));

        UsernameTextField.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        UsernameTextField.setForeground(new java.awt.Color(0, 0, 0));
        UsernameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UsernameTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });
        LoginPanel.add(UsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, 35));

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        UsernameLabel.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\user.png")); // NOI18N
        UsernameLabel.setText("Username");
        UsernameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        LoginPanel.add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 30));

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\padlock.png")); // NOI18N
        PasswordLabel.setText("Password");
        PasswordLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        LoginPanel.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, 30));

        CakeImage.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\cake (1).png")); // NOI18N
        LoginPanel.add(CakeImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        loginBtn.setBackground(new java.awt.Color(93, 56, 10));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        LoginPanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, -1));

        doesnt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        doesnt.setForeground(new java.awt.Color(255, 255, 255));
        doesnt.setText("Doesn't have an account yet?");
        LoginPanel.add(doesnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        signUpBtn.setBackground(new java.awt.Color(93, 56, 10));
        signUpBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        signUpBtn.setForeground(new java.awt.Color(0, 0, 0));
        signUpBtn.setText("Sign Up");
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });
        LoginPanel.add(signUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        PasswordField.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        PasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LoginPanel.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 200, 35));

        MainTabbedPane.addTab("tab2", LoginPanel);

        SignupPanel.setBackground(new java.awt.Color(140, 135, 135,180));
        SignupPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SweetLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        SweetLabel2.setForeground(new java.awt.Color(93, 56, 10));
        SweetLabel2.setText("Sweet ");
        SignupPanel.add(SweetLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 19, -1, -1));

        ManagementLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        ManagementLabel2.setForeground(new java.awt.Color(0, 0, 0));
        ManagementLabel2.setText("Management System");
        SignupPanel.add(ManagementLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 324, 30));

        UsernameLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        UsernameLabel2.setForeground(new java.awt.Color(0, 0, 0));
        UsernameLabel2.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\user.png")); // NOI18N
        UsernameLabel2.setText("Username");
        UsernameLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        SignupPanel.add(UsernameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 30));

        UsernameTextField2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        UsernameTextField2.setForeground(new java.awt.Color(0, 0, 0));
        UsernameTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UsernameTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UsernameTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextField2ActionPerformed(evt);
            }
        });
        SignupPanel.add(UsernameTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 190, 35));

        PasswordLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        PasswordLabel2.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel2.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\padlock.png")); // NOI18N
        PasswordLabel2.setText("Password");
        PasswordLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        SignupPanel.add(PasswordLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 30));

        PasswordTextField2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        PasswordTextField2.setForeground(new java.awt.Color(0, 0, 0));
        PasswordTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PasswordTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextField2ActionPerformed(evt);
            }
        });
        SignupPanel.add(PasswordTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 190, 35));

        ConfirmPassLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        ConfirmPassLabel.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmPassLabel.setText("Confirm Password");
        ConfirmPassLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        SignupPanel.add(ConfirmPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 130, 30));

        ConfirmPassTextField.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        ConfirmPassTextField.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmPassTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ConfirmPassTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ConfirmPassTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPassTextFieldActionPerformed(evt);
            }
        });
        SignupPanel.add(ConfirmPassTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 190, 35));

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(0, 0, 0));
        EmailLabel.setText("Email Address");
        EmailLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        SignupPanel.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, 30));

        EmailTextField.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        EmailTextField.setForeground(new java.awt.Color(0, 0, 0));
        EmailTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EmailTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });
        SignupPanel.add(EmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 190, 35));

        CityLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        CityLabel.setForeground(new java.awt.Color(0, 0, 0));
        CityLabel.setText("City");
        CityLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        SignupPanel.add(CityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 50, 40));

        CityComboBox.setBackground(new java.awt.Color(255, 255, 255));
        CityComboBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CityComboBox.setForeground(new java.awt.Color(0, 0, 0));
        CityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Select", "Jerusalem", " Bethlehem", " Beit Jala", " Beit Sahour", " Hebron", " Sabastia", " Jericho", " Ramallah & El-Bireh", " Nablus", " Tulkarem", " Jenin", " Gaza" }));
        CityComboBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SignupPanel.add(CityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 130, 40));

        SignUpBtnS.setBackground(new java.awt.Color(93, 56, 10));
        SignUpBtnS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SignUpBtnS.setForeground(new java.awt.Color(255, 255, 255));
        SignUpBtnS.setText("Sign Up");
        SignUpBtnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBtnSActionPerformed(evt);
            }
        });
        SignupPanel.add(SignUpBtnS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 180, -1));

        Already.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Already.setForeground(new java.awt.Color(255, 255, 255));
        Already.setText("Already have an account?");
        SignupPanel.add(Already, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        LoginBtnS.setBackground(new java.awt.Color(93, 56, 10));
        LoginBtnS.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LoginBtnS.setForeground(new java.awt.Color(0, 0, 0));
        LoginBtnS.setText("Login");
        LoginBtnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnSActionPerformed(evt);
            }
        });
        SignupPanel.add(LoginBtnS, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 437, -1, -1));

        UserCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        UserCheckBox.setText("User");
        UserCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserCheckBoxActionPerformed(evt);
            }
        });
        SignupPanel.add(UserCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        OwnerCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OwnerCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        OwnerCheckBox.setText("Owner");
        OwnerCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OwnerCheckBoxActionPerformed(evt);
            }
        });
        SignupPanel.add(OwnerCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        SupplierCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SupplierCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        SupplierCheckBox.setText("Supplier");
        SupplierCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierCheckBoxActionPerformed(evt);
            }
        });
        SignupPanel.add(SupplierCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        MainTabbedPane.addTab("tab2", SignupPanel);

        getContentPane().add(MainTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, -40, 370, 520));

        BackgroundImage.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\Background1.jpg")); // NOI18N
        getContentPane().add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
        if(UsernameTextField.getText().equals("") || PasswordField.getPassword().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter a valid Username and Password!", null, JOptionPane.ERROR_MESSAGE);
        }
        else if(UsernameTextField.getText().equals("Admin") && PasswordField.getText().equals("123"))
        {
           this.dispose();
           new AdminFrame().setVisible(true);
        } 
        else if(UsernameTextField.getText().equals("Supplier") && PasswordField.getText().equals("123"))
        {
           this.dispose();
           new RawMaterialSupplierFrame().setVisible(true);
        } 
        else if(UsernameTextField.getText().equals("Owner") && PasswordField.getText().equals("123"))
        {
           this.dispose();
           new StoreOwnerFrame().setVisible(true);
        } 
        else if(UsernameTextField.getText().equals("User") && PasswordField.getText().equals("123"))
        {
           this.dispose();
           new UserFrame().setVisible(true);
        } 
        else 
            JOptionPane.showMessageDialog(null, "Please enter a valid Username and Password!", null, JOptionPane.ERROR_MESSAGE);
    }                                        

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
       MainTabbedPane.setSelectedIndex(1);
    }                                         

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void ConfirmPassTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void UsernameTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void PasswordTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void SignUpBtnSActionPerformed(java.awt.event.ActionEvent evt) {                                           


    }                                          

    private void LoginBtnSActionPerformed(java.awt.event.ActionEvent evt) {                                          
        MainTabbedPane.setSelectedIndex(0);
    }                                         

    private void UserCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {                                             
        SupplierCheckBox.setSelected(false);
        OwnerCheckBox.setSelected(false);

        
        
    }                                            

    private void SupplierCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        UserCheckBox.setSelected(false);
        OwnerCheckBox.setSelected(false);
    }                                                

    private void OwnerCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {                                              
        SupplierCheckBox.setSelected(false);
        UserCheckBox.setSelected(false);
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Already;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel CakeImage;
    private javax.swing.JComboBox<String> CityComboBox;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JLabel ConfirmPassLabel;
    private javax.swing.JTextField ConfirmPassTextField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JButton LoginBtnS;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JTabbedPane MainTabbedPane;
    private javax.swing.JLabel ManagementLabel;
    private javax.swing.JLabel ManagementLabel2;
    private javax.swing.JCheckBox OwnerCheckBox;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordLabel2;
    private javax.swing.JTextField PasswordTextField2;
    private javax.swing.JButton SignUpBtnS;
    private javax.swing.JPanel SignupPanel;
    private javax.swing.JCheckBox SupplierCheckBox;
    private javax.swing.JLabel SweetLabel;
    private javax.swing.JLabel SweetLabel2;
    private javax.swing.JCheckBox UserCheckBox;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel UsernameLabel2;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JTextField UsernameTextField2;
    private javax.swing.JLabel doesnt;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton signUpBtn;
    // End of variables declaration                   
}
