/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.software.ui;

/**
 *
 * @author Omar Khatib
 */
public class UserFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserFrame
     */
    public UserFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        SupplierTabbedPane = new javax.swing.JTabbedPane();
        WelcomePanel = new javax.swing.JPanel();
        UserManagementPanel = new javax.swing.JPanel();
        UserManageTools = new javax.swing.JPanel();
        ManageAccLabel = new javax.swing.JLabel();
        UserMngUsernameTxt = new javax.swing.JTextField();
        UserMngPasswordTxt = new javax.swing.JTextField();
        UserMngEmailTxt = new javax.swing.JTextField();
        UserMngCityTxt = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        OkButton = new javax.swing.JButton();
        SolidLineLabel = new javax.swing.JLabel();
        ProductsPanel = new javax.swing.JPanel();
        ProductsTools = new javax.swing.JPanel();
        ProductsLabel = new javax.swing.JLabel();
        SolidLineLabel1 = new javax.swing.JLabel();
        ShowPostsBtn = new javax.swing.JButton();
        ProductFeedBackBtn = new javax.swing.JButton();
        ShowRecipeBtn = new javax.swing.JButton();
        RecipeFeedbackBtn = new javax.swing.JButton();
        AllergicCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrdersTxtArea = new javax.swing.JTextArea();
        SupplierBtnsPanel = new javax.swing.JPanel();
        MngAccountBtn = new javax.swing.JButton();
        ProductsBtn = new javax.swing.JButton();
        OrdersBtn = new javax.swing.JButton();
        RecipesBtn = new javax.swing.JButton();
        CommunicationBtn = new javax.swing.JButton();
        NotificationsBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        WelcomeSupplierLabel = new javax.swing.JLabel();
        CakeImage = new javax.swing.JLabel();
        CE121Label = new javax.swing.JLabel();
        BackgroundPanel = new javax.swing.JPanel();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SupplierTabbedPane.setBackground(new java.awt.Color(255, 255, 255,0));

        WelcomePanel.setBackground(new java.awt.Color(255, 255, 255,0));

        javax.swing.GroupLayout WelcomePanelLayout = new javax.swing.GroupLayout(WelcomePanel);
        WelcomePanel.setLayout(WelcomePanelLayout);
        WelcomePanelLayout.setHorizontalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        WelcomePanelLayout.setVerticalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );

        SupplierTabbedPane.addTab("tab4", WelcomePanel);

        UserManagementPanel.setBackground(new java.awt.Color(255, 255, 255,0));

        UserManageTools.setBackground(new java.awt.Color(153, 153, 153,180));

        ManageAccLabel.setBackground(new java.awt.Color(0, 0, 0));
        ManageAccLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ManageAccLabel.setForeground(new java.awt.Color(0, 0, 0));
        ManageAccLabel.setText("Manage Account");

        UserMngUsernameTxt.setBackground(new java.awt.Color(255, 255, 255));
        UserMngUsernameTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserMngUsernameTxt.setForeground(new java.awt.Color(0, 0, 0));

        UserMngPasswordTxt.setBackground(new java.awt.Color(255, 255, 255));
        UserMngPasswordTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserMngPasswordTxt.setForeground(new java.awt.Color(0, 0, 0));

        UserMngEmailTxt.setBackground(new java.awt.Color(255, 255, 255));
        UserMngEmailTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserMngEmailTxt.setForeground(new java.awt.Color(0, 0, 0));

        UserMngCityTxt.setBackground(new java.awt.Color(255, 255, 255));
        UserMngCityTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserMngCityTxt.setForeground(new java.awt.Color(0, 0, 0));

        UsernameLabel.setBackground(new java.awt.Color(0, 0, 0));
        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        UsernameLabel.setText("Username:");

        EmailLabel.setBackground(new java.awt.Color(0, 0, 0));
        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(0, 0, 0));
        EmailLabel.setText("Email:");

        PasswordLabel.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel.setText("Password:");

        CityLabel.setBackground(new java.awt.Color(0, 0, 0));
        CityLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CityLabel.setForeground(new java.awt.Color(0, 0, 0));
        CityLabel.setText("City:");

        OkButton.setBackground(new java.awt.Color(6, 134, 161));
        OkButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        OkButton.setForeground(new java.awt.Color(0, 0, 0));
        OkButton.setText("OK");

        SolidLineLabel.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\Line.png")); // NOI18N

        javax.swing.GroupLayout UserManageToolsLayout = new javax.swing.GroupLayout(UserManageTools);
        UserManageTools.setLayout(UserManageToolsLayout);
        UserManageToolsLayout.setHorizontalGroup(
            UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserManageToolsLayout.createSequentialGroup()
                .addGroup(UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserManageToolsLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(ManageAccLabel))
                    .addGroup(UserManageToolsLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(UserManageToolsLayout.createSequentialGroup()
                                .addComponent(UsernameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserMngUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UserManageToolsLayout.createSequentialGroup()
                                .addComponent(EmailLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserMngEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(104, 104, 104)
                        .addGroup(UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(UserManageToolsLayout.createSequentialGroup()
                                .addComponent(CityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserMngCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UserManageToolsLayout.createSequentialGroup()
                                .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserMngPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(UserManageToolsLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(SolidLineLabel)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserManageToolsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(325, 325, 325))
        );
        UserManageToolsLayout.setVerticalGroup(
            UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserManageToolsLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(ManageAccLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SolidLineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserMngPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserMngUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(UserManageToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserMngCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserMngEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(OkButton)
                .addGap(133, 133, 133))
        );

        javax.swing.GroupLayout UserManagementPanelLayout = new javax.swing.GroupLayout(UserManagementPanel);
        UserManagementPanel.setLayout(UserManagementPanelLayout);
        UserManagementPanelLayout.setHorizontalGroup(
            UserManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserManagementPanelLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(UserManageTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        UserManagementPanelLayout.setVerticalGroup(
            UserManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserManagementPanelLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(UserManageTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        SupplierTabbedPane.addTab("tab1", UserManagementPanel);

        ProductsPanel.setBackground(new java.awt.Color(255, 255, 255,0));

        ProductsTools.setBackground(new java.awt.Color(153, 153, 153,180));

        ProductsLabel.setBackground(new java.awt.Color(0, 0, 0));
        ProductsLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ProductsLabel.setForeground(new java.awt.Color(0, 0, 0));
        ProductsLabel.setText("Products & Recipes");

        SolidLineLabel1.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\Line.png")); // NOI18N

        ShowPostsBtn.setBackground(new java.awt.Color(6, 134, 161));
        ShowPostsBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ShowPostsBtn.setForeground(new java.awt.Color(0, 0, 0));
        ShowPostsBtn.setText("Show Posts");

        ProductFeedBackBtn.setBackground(new java.awt.Color(6, 134, 161));
        ProductFeedBackBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ProductFeedBackBtn.setForeground(new java.awt.Color(0, 0, 0));
        ProductFeedBackBtn.setText("Product Feedback");

        ShowRecipeBtn.setBackground(new java.awt.Color(6, 134, 161));
        ShowRecipeBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ShowRecipeBtn.setForeground(new java.awt.Color(0, 0, 0));
        ShowRecipeBtn.setText("Show Recipes");

        RecipeFeedbackBtn.setBackground(new java.awt.Color(6, 134, 161));
        RecipeFeedbackBtn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        RecipeFeedbackBtn.setForeground(new java.awt.Color(0, 0, 0));
        RecipeFeedbackBtn.setText("Recipe Feedback");

        AllergicCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AllergicCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        AllergicCheckBox.setText("Allergic");
        AllergicCheckBox.setToolTipText("");

        OrdersTxtArea.setColumns(20);
        OrdersTxtArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OrdersTxtArea.setForeground(new java.awt.Color(0, 0, 0));
        OrdersTxtArea.setRows(5);
        jScrollPane1.setViewportView(OrdersTxtArea);

        javax.swing.GroupLayout ProductsToolsLayout = new javax.swing.GroupLayout(ProductsTools);
        ProductsTools.setLayout(ProductsToolsLayout);
        ProductsToolsLayout.setHorizontalGroup(
            ProductsToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductsToolsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ProductsToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AllergicCheckBox)
                    .addGroup(ProductsToolsLayout.createSequentialGroup()
                        .addGroup(ProductsToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ShowPostsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShowRecipeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(ProductsToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RecipeFeedbackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductFeedBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(127, 127, 127))
            .addGroup(ProductsToolsLayout.createSequentialGroup()
                .addGroup(ProductsToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductsToolsLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(SolidLineLabel1))
                    .addGroup(ProductsToolsLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(ProductsLabel))
                    .addGroup(ProductsToolsLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        ProductsToolsLayout.setVerticalGroup(
            ProductsToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductsToolsLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(ProductsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SolidLineLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AllergicCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProductsToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductFeedBackBtn)
                    .addComponent(ShowPostsBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductsToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RecipeFeedbackBtn)
                    .addComponent(ShowRecipeBtn))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout ProductsPanelLayout = new javax.swing.GroupLayout(ProductsPanel);
        ProductsPanel.setLayout(ProductsPanelLayout);
        ProductsPanelLayout.setHorizontalGroup(
            ProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductsPanelLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(ProductsTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        ProductsPanelLayout.setVerticalGroup(
            ProductsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductsPanelLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(ProductsTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        SupplierTabbedPane.addTab("tab2", ProductsPanel);

        getContentPane().add(SupplierTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -40, 1080, 840));

        SupplierBtnsPanel.setBackground(new java.awt.Color(255, 255, 255,150));
        SupplierBtnsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MngAccountBtn.setBackground(new java.awt.Color(6, 134, 161));
        MngAccountBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MngAccountBtn.setForeground(new java.awt.Color(0, 0, 0));
        MngAccountBtn.setText("Manage Account");
        MngAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MngAccountBtnActionPerformed(evt);
            }
        });
        SupplierBtnsPanel.add(MngAccountBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 100, 257, 70));

        ProductsBtn.setBackground(new java.awt.Color(6, 134, 161));
        ProductsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProductsBtn.setForeground(new java.awt.Color(0, 0, 0));
        ProductsBtn.setText("Products");
        ProductsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductsBtnActionPerformed(evt);
            }
        });
        SupplierBtnsPanel.add(ProductsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 180, 260, 70));

        OrdersBtn.setBackground(new java.awt.Color(6, 134, 161));
        OrdersBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        OrdersBtn.setForeground(new java.awt.Color(0, 0, 0));
        OrdersBtn.setText("Orders");
        OrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersBtnActionPerformed(evt);
            }
        });
        SupplierBtnsPanel.add(OrdersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 260, 257, 70));

        RecipesBtn.setBackground(new java.awt.Color(6, 134, 161));
        RecipesBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RecipesBtn.setForeground(new java.awt.Color(0, 0, 0));
        RecipesBtn.setText("Recipes");
        RecipesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecipesBtnActionPerformed(evt);
            }
        });
        SupplierBtnsPanel.add(RecipesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 340, 257, 70));

        CommunicationBtn.setBackground(new java.awt.Color(6, 134, 161));
        CommunicationBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CommunicationBtn.setForeground(new java.awt.Color(0, 0, 0));
        CommunicationBtn.setText("Communication");
        CommunicationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunicationBtnActionPerformed(evt);
            }
        });
        SupplierBtnsPanel.add(CommunicationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 420, 257, 70));

        NotificationsBtn.setBackground(new java.awt.Color(6, 134, 161));
        NotificationsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NotificationsBtn.setForeground(new java.awt.Color(0, 0, 0));
        NotificationsBtn.setText("Notifications");
        NotificationsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificationsBtnActionPerformed(evt);
            }
        });
        SupplierBtnsPanel.add(NotificationsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 500, 257, 70));

        LogOutBtn.setBackground(new java.awt.Color(236, 170, 73));
        LogOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LogOutBtn.setForeground(new java.awt.Color(0, 0, 0));
        LogOutBtn.setText("Logout");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        SupplierBtnsPanel.add(LogOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 580, 257, 70));

        WelcomeSupplierLabel.setBackground(new java.awt.Color(0, 0, 0));
        WelcomeSupplierLabel.setFont(new java.awt.Font("MV Boli", 1, 28)); // NOI18N
        WelcomeSupplierLabel.setText("Welcome User");
        WelcomeSupplierLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WelcomeSupplierLabelMouseClicked(evt);
            }
        });
        SupplierBtnsPanel.add(WelcomeSupplierLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 61));

        CakeImage.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\cake (1).png")); // NOI18N
        SupplierBtnsPanel.add(CakeImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 680, -1, -1));

        CE121Label.setBackground(new java.awt.Color(0, 0, 0));
        CE121Label.setFont(new java.awt.Font("Pristina", 1, 14)); // NOI18N
        CE121Label.setText("CE.121");
        SupplierBtnsPanel.add(CE121Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 730, 40, -1));

        getContentPane().add(SupplierBtnsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 800));

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255,0));

        BackgroundImage.setIcon(new javax.swing.ImageIcon("src\\main\\resources\\Images\\Background4.jpg")); // NOI18N

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BackgroundImage)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BackgroundImage)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(BackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void MngAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {                                              
        SupplierTabbedPane.setSelectedIndex(1);
    }                                             

    private void ProductsBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        SupplierTabbedPane.setSelectedIndex(2);
    }                                           

    private void OrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        SupplierTabbedPane.setSelectedIndex(0);
    }                                         

    private void CommunicationBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        SupplierTabbedPane.setSelectedIndex(0);
    }                                                

    private void NotificationsBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        SupplierTabbedPane.setSelectedIndex(0);
    }                                                

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.dispose();
        new LoginFrame().setVisible(true);
    }                                         

    private void WelcomeSupplierLabelMouseClicked(java.awt.event.MouseEvent evt) {                                                  
        SupplierTabbedPane.setSelectedIndex(0);
    }                                                 

    private void RecipesBtnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        SupplierTabbedPane.setSelectedIndex(0);
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox AllergicCheckBox;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel CE121Label;
    private javax.swing.JLabel CakeImage;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JButton CommunicationBtn;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JLabel ManageAccLabel;
    private javax.swing.JButton MngAccountBtn;
    private javax.swing.JButton NotificationsBtn;
    private javax.swing.JButton OkButton;
    private javax.swing.JButton OrdersBtn;
    private javax.swing.JTextArea OrdersTxtArea;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton ProductFeedBackBtn;
    private javax.swing.JButton ProductsBtn;
    private javax.swing.JLabel ProductsLabel;
    private javax.swing.JPanel ProductsPanel;
    private javax.swing.JPanel ProductsTools;
    private javax.swing.JButton RecipeFeedbackBtn;
    private javax.swing.JButton RecipesBtn;
    private javax.swing.JButton ShowPostsBtn;
    private javax.swing.JButton ShowRecipeBtn;
    private javax.swing.JLabel SolidLineLabel;
    private javax.swing.JLabel SolidLineLabel1;
    private javax.swing.JPanel SupplierBtnsPanel;
    private javax.swing.JTabbedPane SupplierTabbedPane;
    private javax.swing.JPanel UserManageTools;
    private javax.swing.JPanel UserManagementPanel;
    private javax.swing.JTextField UserMngCityTxt;
    private javax.swing.JTextField UserMngEmailTxt;
    private javax.swing.JTextField UserMngPasswordTxt;
    private javax.swing.JTextField UserMngUsernameTxt;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JLabel WelcomeSupplierLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
